---
- hosts: ant-hill

  vars:
    ssh_authorized_keys:
    - 'ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQC0HxL8p3GBMC0pztwrk2Xqgrtezzk2aIDCev+lgWYNpsaULh5+XWM3/NnJx8GaLG2ObtFxD+kbhifpi6FMwgrsSaaW7Lc5ua2ZTy3qcXAW8VkYO+5MBEkCllSgl3AXkGEbyoE29qc6ZtNLL2U083oTGqppNao3PLW+3/4WyYJ4kHjvy/2bWLB745aQUUsiXJt7Juxm8SPbWXIfFqKrQGt20e6LYwUcnA1FlMSL03dPJ6AMAvJUTl/j6N2LcNFztl75EiYNhNptBE6t8SwsTvMa/GpDlvMXiC7z8iPn6MsqqyoGv74nyVMeD9Z23vnOz/UmrL4rNN921h1JwuJPRagr jakub@Jakubs-MacBook-Pro.local'
    - 'ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQDoGCusJ2rjm051rV2TAtyZsA/sc0g6jEXy2LEsG29xWN+Dt3E5rmwE1CMZ7sQBsUfruIcacdnLj+6804JztZSCMUG8dFYIuZDsL0SrRHacGztnBZBMpcEPBADM67RynXtNdCKkKbV86OPglb0HwRb8W/Q3ox4NgMcLN0S/pcFUnD2FopJ5lokNwagkj/qCQB9DeKwxXfghYC+hj+6c2EuSN0uz2ifdK2Ockge73aF3xz2exlcw5yK1h4T3Fx/7nl5Oy8noQCJfxI+kKyun6udnYpko7GcV1c/3doL8JRxVXDfO0GguhMva4yFiL1gFCPvsPSlohc1jD9q0pXnwEUOH jakob@SFO-M-JDYSZKIEWICZ01.local'
  vars_files:
  - vars/secrets.yaml

  tasks:
  - name: Install dotfiles
    include_role:
      name: dotfiles
  # - name: Install VPN (tailscale) # auth key is encrypted in vars/secrets.yaml
  #   include_role:
  #     name: artis3n.tailscale
  # it fails for some reason 🤔
  - name: Decrypt backup volume
    become: true
    community.crypto.luks_device:
      device: /dev/sda # # TODO should this be by ID?
      state: opened
      name: backup
      passphrase: "{{ luks_volumes_passphrase }}"
  - name: Decrypt data volume
    become: true
    community.crypto.luks_device:
      device: /dev/nvme0n1p4 # TODO should this be by ID?
      state: opened
      name: data
      passphrase: "{{ luks_volumes_passphrase }}"
  - name: Provision ant-dev VM
    include_role:
      name: vm_provision
    vars:
      vm_name: 'ant-dev'
      vm_net_mac: '52:54:00:ef:39:12'
      vm_net_ip: '192.168.1.51'
      vm_vcpus: 14
      vm_ram_mb: 16384
      vm_disk_size: 100G
  - name: Provision ant-services VM
    include_role:
      name: vm_provision
    vars:
      vm_name: 'ant-services'
      vm_net_mac: '52:54:00:ef:39:13'
      vm_net_ip: '192.168.1.52'
      vm_vcpus: 8
      vm_ram_mb: 8192
      vm_disk_size: 100G
      disk_mappings: 
      - source_dev: /dev/mapper/data
        target_dev: vdb
      - source_dev: /dev/sdb1
        target_dev: vdc
      - source_dev: /dev/mapper/backup
        target_dev: vdd
