---
- hosts: ant-dev
  vars_files:
  - vars/secrets.yaml
  tasks:
  - name: Install mDNS Discovery
    become: yes
    apt:
      pkg:
      - avahi-daemon
      state: latest
      update_cache: true
      cache_valid_time: 86400 # One day
  - name: Install dotfiles
    include_role:
      name: dotfiles
  - name: Install Kong development environment
    include_role:
      name: kong-dev
  # - name: Install VPN (tailscale) # auth key is encrypted in vars/secrets.yaml
  #   include_role:
  #     name: artis3n.tailscale