---
base_image_name: jammy-server-cloudimg-amd64.img
base_image_url: "https://cloud-images.ubuntu.com/jammy/current/{{ base_image_name }}"
base_image_sha: 1b78127cd4bccf943cd43ee7489b5d96a73028e2835d2f8d8d41c8e8ef47a825
libvirt_pool_dir: "/var/lib/libvirt/images"
vm_name: ant_test
vm_vcpus: 2
vm_ram_mb: 2048
vm_disk_size: 5G
vm_net_mac: '52:54:00:ef:39:11'
vm_net_ip: '192.168.1.60'
vm_net_gateway: '192.168.1.1'
vm_net_host_bridge: vmbridge0
vm_root_password: test123
images_dir: /opt/images
cleanup_images: no
ssh_authorized_keys: []
disk_mappings: []
usb_mappings: []