global:
  scrape_interval:     15s
  evaluation_interval: 15s
scrape_configs:
  - job_name: 'nodeexporter'
    scrape_interval: 10s
    static_configs:
      - targets: ['host.docker.internal:9100']
  - job_name: 'cadvisor'
    scrape_interval: 10s
    static_configs:
      - targets: ['cadvisor:8080']
  - job_name: 'speedtest-exporter'
    scrape_interval: 1h
    scrape_timeout: 1m
    static_configs:
      - targets: ['speedtest:9090']